export const REQUEST_FETCH_AGEN = "REQUEST_FETCH_AGEN";
export const FETCH_AGEN = "FETCH_AGEN";
export const FAILURE_FETCH_AGEN = "FAILURE_FETCH_AGEN";
export const SET_AGEN = "SET_AGEN";

export const REQUEST_FETCH_CART = "REQUEST_FETCH_CART";
export const FETCH_CART = "FETCH_CART";
export const FAILURE_FETCH_CART = "FAILURE_FETCH_CART";
export const ADD_CART = "ADD_CART";
export const UPDATE_CART = "UPDATE_CART";
export const SUB_QUANTITY = "SUB_QUANTITY";
export const REMOVE_CART = "REMOVE_CART";

export const REQUEST_FETCH_ACCOUNT = "REQUEST_FETCH_ACCOUNT";
export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FAILURE_FETCH_ACCOUNT = "FAILURE_FETCH_ACCOUNT";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";

export const REQUEST_FETCH_ALAMAT = "REQUEST_FETCH_ALAMAT";
export const FETCH_ALAMAT = "FETCH_ALAMAT";
export const SET_ALAMAT = "SET_ALAMAT";
export const FAILURE_FETCH_ALAMAT = "FAILURE_FETCH_ALAMAT";

 // Seller

export const DAFTAR_RESELLER = 'DAFTAR_RESELLER';
export const DOCUMENT_RESELLER = 'DOCUMENT_RESELLER';
export const DATA_RESELLER = 'DATA_RESELLER';
export const ADD_TOP_CATEGORY = 'ADD_TOP_CATEGORY';
export const ADD_SUB_CATEGORY = 'ADD_SUB_CATEGORY';
export const ADD_SUB_CATEGORY2 = 'ADD_SUB_CATEGORY2';
export const ADD_COLOR_VARIAN = 'ADD_COLOR_VARIAN';
export const ADD_SIZE_VARIAN = 'ADD_SIZE_VARIAN';